### ISSUE TITLE
Reward all players button

### ISSUE THREAD

**Issue by sSeur** [elizeuangelo/fvtt-module-hero-points-faq#2]
Hi, I really like how the module works, so I would like to suggest a keybinding or a button where I could give a point to all my players at once. Additionally, it would be helpful to have some way to keep track of the points. I would appreciate it.

**Comment by elizeuangelo** [comment]
Please checkout the latest release: v1.1.1

It introduces a "Hero Points" button on the footer of the Actor's directory.
