### ISSUE TITLE
Add macros to award hero points to all players [feat]

### ISSUE THREAD

**Issue by TheSabotender** [elizeuangelo/fvtt-module-hero-points-faq#4]
Sometimes, I would like to award all players with Hero Points at the same time.  Currently, it is tedious to reward each character individually.

Please add a Macro to award all players simultaneously, this Macro should display a popup asking if the DM wants to Add or Remove points, as well as how many points.

**Comment by elizeuangelo** [comment]
Hello TheSabotender!

There is already a button to reward all players at the same time. It's on the footer of the actor directory:
![image](https://github.com/elizeuangelo/fvtt-module-hero-points-faq/assets/56921633/56646310-93dc-4d0a-b901-6c4309e51633)
![image](https://github.com/elizeuangelo/fvtt-module-hero-points-faq/assets/56921633/39aa8d0a-b6b3-4c50-8ecc-454c2b4fcd0e)

**Comment by TheSabotender** [comment]
ahh amazing, didn not see that :D
